language: node_js
node_js:
- 11
before_install:
- cd frontend
- npm install
- cd ..
script:
- npm test
- npm run build:front
deploy:
  provider: heroku:git
  username: remotesocietynow@protonmail.com
  password:
    secure: wETYUIOQ6z1A1K58M6IVyo2iBtwY3d8jkmbZly1707NtmlwwkvemuV6xOLWz2XAZUuS4S+C3qMQ948VvHXWSgdGIvYRWqfpJnIAzY3fWgNVCpxKGIotQAYBQM6zEVYxRHzfIUlbyTU9Xadgs3yT8w9u63SkwsXH45vemWjmfivSbXXp8vltdWAVjbV6iZbY8vq1dLUTllLwrEKp0J4qDKTp+/Sp75ZJPIzeb+uMEHFDiNR49v35I+OkcQoBKYThbJ45n5+to4jcuSst2pRMuv4Z8mFV9SEFXyeqSePqzCZ/+jlvTp8A7hlZa4bxnWR8OogYgrw9yM8JY1nTmApEMpe8utOS3O6Bn23tuq2WYM5+MeKC/A/TKv5M6ZPCHnpJthr4EW8/qutzEgwLiUlcrEkTJoYNhpbLK/uotoRk9LrJ6tadA0JE8pR4qoq+ZvcRHuoS9vC/ZcFiqSHv/43LD9uRNo4EuKy6pCGm4doJamom+jIpzlzl2e0ysMGOCZSPibV/gTNmcvfiRSEvJfxHobRd6H2KVtsdgUJzXZryp2G1Ajv2275n8ZtFPbsq+fS21FJ7WtcA6kdPKdb3SiGXDcDJ+Uac4n0mSW+AxtDpw2/EL+kyIc8m/79PMeqVh+nFvNufgM4BlvL1bv3tIw026wMemSLFEW0+EMJzCmlUdbs0=
  edge: true
