language: node_js
node_js:
- 11
before_install:
- cd frontend
- npm install
- cd ..
script:
- npm test
- npm run build:front
deploy:
  provider: heroku
  api_key:
    secure: UK4eAECLC7luAVVnkqDh3p6lLQvbQswtjyn4toznRU9BQT/JpXCSU5KLRgiUTPqW7SBDDwkD78APlRAfuAOIfwbp94QVggkQsfZYObFl5F4owfPZD76YO3x4PWamoXrvXHW2Dc3bMfQNhAMbHpUYMcuHtlR8ueTuuhQYhvRuCDe5tKiwUgNduOf5mG2A9HvgFAySwZfNg3peQKWWRE09QIr7Qa+vODvNH32/c9s1jB75DkHBeAq/g5LssyrQNPYo6l0feETtvA3O1A9/U4Uk97/WUCD0H+YBgJ1Foq/vO9W8mYcxJZANgasHZ9KN6Rm4XaOntFqFF1Idg89MpVqFj1y6Asin3U9q2Iw8oAVtIV0MnEQx79ws6VhyIHZS3clS7834FkMIzqPwcrKsrmCpLNwPxkpjWaPPC0XC19g+7exuyZXjG3eJb2D7USlG8L9atg5QEPPqh52mjACiVe8lYp/qMhW/7vFbAyrm+5M1Rh8MN/u9AsQUgEyg78Xd0Gedg1VXstTVOjf49HhJ3qPhjpjvP5Va/yIyHovgV+FSPDVwzaUrxtdddq/boGhEslgqeL1QOBmgGzf7g2co1ctU9NRSEkgs7zSIV6QJCFoCGP2CdeORsf1d2UzTssppecPlFFNKbXoBHC0ItWaXm8UYKHnHhqEU71TuEgSFrn380DY=
  app: remotesocietynow
  on:
    repo: RemoteSocietyNow-ohtu/remotesocietynow
  skip_cleanup: 'true'
