language: node_js
node_js:
- 11
before_install:
- cd frontend
- npm install
- cd ..
script:
- npm test
- npm run build:front
deploy:
  provider: heroku:git
  username: remotesocietynow@protonmail.com
  password: 
    secure: "d0GqWNPX7eUvg7+k7NQKQjFpPQe3yyaTVzbyaaLKrJJLvFDU8RyahBE/7JnXkLCkJPEBMKrT48Tat6039+HZOTi4h0nin69GPpinVWjFslmRIU1/wmyuwqY93pPkPuiedu2+r6wuj7bRWjQZzHFEd5J6GR7b6ViD04yjEM1Ig4sZb40zol274jKNhsfuUqJTbpL78coFL6eOmzRhDptBFfk4W4Vt8t/BN+bWwTrUgs8TRceQZvcIlJpEDK31lWPlhmcyxudZldXi/1/s8lir35YQd+gTmu4g9x6Q8CGhgWJaGUp5LBuFmtogGpB6x3ESVOLUKNdLWlGUO7dbtPlL765mX5CVxZQljIBv2ow4/qxfgXycbVv136W5rRCKP7v3eDVF8I57Gt3MpM8lCMUs9chYzrMaV6izOuuuGN1hTDpyA0xkBAnHZziWCPb4igHAyLWiO06pEYmaTfgcHK3q3DBda3q1LRjVLgvnJGVhucR4cJhRI/OTMaC1ZQJd1fHBuFlETbxXsbSpGLQlfql86yKWh7PH7GmL+4XXayL+24iUUB9RHCYQ9kky3pgQOb9/0wrIXqjU9CL2PYesrPeRbvv4lXwmdQVCW+5iu5WLBc9Fkeu4ofd8RI6j0qRwqp5H+aSMQwFXHygRtzAphJPadf9oE0VORyMf3RIBQ1vlk7Q="
  edge: true
