language: node_js
node_js:
- 11
before_install:

script:
- npm run test
- npm run fix:lint
- npm run lint
- npm run build
env:
  global: 
    - secure: "AmzInYt5KWS0aYnOixKt8s8W3tdjU9UKbjBPa/uG1w6XrTgqM+bpdEbeoNMf7ihas/OHN8x9miOaZA9lv8jsMXnKb2NGJSZrjiCD98PvFVkgaAU9fX21uRQyRYmMcPSz8TEoDaT2nObvzfptYwM59ld2GL+O1ccxbM3Yv2+1Vm1vol4knt7FK7q+msMchKR3s3nEQymuE/+O1dsioxC8Nmxu9Luc4hV/U5siyGHl6YGHlDczw59/tfHXlSoT347BB1k/TDDkExtAsLF0jffee44cccQJYaylOIN1OOs3yv9zW8V2ou3d98QZSg8X0pNX9B8GgPUG5T6JUXC9oLuBdqCYKQGpb8WjsNr3afU0G6uHwne+H/2orfHW0eyu/AKWHBMP0LmLUC5ZZ77lBUYh57SwqLWO0N9juWQixXdV/wekh52oKS+WFfOtiuFrFmPOuRPcvodEySSDSCpDsHLUtGSLuLgEPTcUWEU7WmK3FNeJr929zPM3jDy2RzVOzgq+TyB4AhKPuAvfMLe3wP49sHlB6RuZ4hPpX3Dbu8/Cpt37A61AQzp+i1OcDveIeXfzuGwq87SkcDqb6wUFfY7IUSUPyNJYSeTMpUNSxj1qiDtbrdhScwdp1yIl1LIBbNrnNgbQ7bFJXcFMooVZd4lQ2BCMUHipglKAt7Tr2pEc34s="
deploy:
  provider: heroku
  api_key:
    secure: UK4eAECLC7luAVVnkqDh3p6lLQvbQswtjyn4toznRU9BQT/JpXCSU5KLRgiUTPqW7SBDDwkD78APlRAfuAOIfwbp94QVggkQsfZYObFl5F4owfPZD76YO3x4PWamoXrvXHW2Dc3bMfQNhAMbHpUYMcuHtlR8ueTuuhQYhvRuCDe5tKiwUgNduOf5mG2A9HvgFAySwZfNg3peQKWWRE09QIr7Qa+vODvNH32/c9s1jB75DkHBeAq/g5LssyrQNPYo6l0feETtvA3O1A9/U4Uk97/WUCD0H+YBgJ1Foq/vO9W8mYcxJZANgasHZ9KN6Rm4XaOntFqFF1Idg89MpVqFj1y6Asin3U9q2Iw8oAVtIV0MnEQx79ws6VhyIHZS3clS7834FkMIzqPwcrKsrmCpLNwPxkpjWaPPC0XC19g+7exuyZXjG3eJb2D7USlG8L9atg5QEPPqh52mjACiVe8lYp/qMhW/7vFbAyrm+5M1Rh8MN/u9AsQUgEyg78Xd0Gedg1VXstTVOjf49HhJ3qPhjpjvP5Va/yIyHovgV+FSPDVwzaUrxtdddq/boGhEslgqeL1QOBmgGzf7g2co1ctU9NRSEkgs7zSIV6QJCFoCGP2CdeORsf1d2UzTssppecPlFFNKbXoBHC0ItWaXm8UYKHnHhqEU71TuEgSFrn380DY=
  app: remotesocietynow
  on:
    repo: RemoteSocietyNow-ohtu/remotesocietynow
  skip_cleanup: 'true'
