const peopleAnswers = {
  monthlyCommuteExpenses: '',
  monthlyCommuteExpensesOpenField: 'Kommenttia',
  dailyCommuteKm: 20,
  dailyCommuteKmOpenField: '',
  dailyCommuteMinutes: '',
  dailyCommuteMinutesOpenField: '',
  noOfDaysOfUsage: 5,
  noOfDaysOfUsageOpenField: '',
  noOfDaysOfUsageSecond: '0',
  noOfDaysOfUsageSecondOpenField: '',
  numberOfBusinessTrips: '',
  numberOfBusinessTripsOpenField: '',
  numberOfHoursOnPlane: '',
  numberOfHoursOnPlaneOpenField: '',
  numberOfRemoteworkDays: '0',
  numberOfRemoteworkDaysOpenField: '',
  opinionRemote: '',
  opinionRemoteOpenField: '',
  secondVehicle: 'walking',
  secondVehicleOpenField: '',
  typicalVehicle: 'car',
  typicalVehicleOpenField: '',
  numberOfHoursOnplane: '',
  numberOfHoursOnplaneOpenField: '' 
}

const peopleAnswersAllCommentFieldsEmpty = {
  monthlyCommuteExpenses: '',
  monthlyCommuteExpensesOpenField: '',
  dailyCommuteKm: 20,
  dailyCommuteKmOpenField: '',
  dailyCommuteMinutes: '',
  dailyCommuteMinutesOpenField: '',
  noOfDaysOfUsage: 5,
  noOfDaysOfUsageOpenField: '',
  noOfDaysOfUsageSecond: '0',
  noOfDaysOfUsageSecondOpenField: '',
  numberOfBusinessTrips: '',
  numberOfBusinessTripsOpenField: '',
  numberOfHoursOnPlane: '',
  numberOfHoursOnPlaneOpenField: '',
  numberOfRemoteworkDays: '0',
  numberOfRemoteworkDaysOpenField: '',
  opinionRemote: '',
  opinionRemoteOpenField: '',
  secondVehicle: 'walking',
  secondVehicleOpenField: '',
  typicalVehicle: 'car',
  typicalVehicleOpenField: '',
  numberOfHoursOnplane: '',
  numberOfHoursOnplaneOpenField: '' 
}

module.exports = { peopleAnswers, peopleAnswersAllCommentFieldsEmpty}